# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AbodeifCheck24' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for AbodeifCheck24
  pod 'Cosmos', '~> 19.0'

  target 'AbodeifCheck24Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
